# routing/ml_predictor.py
# ============================================================
# ML Prediction Module — serves Phase 7's 3-month biomass/capacity
# forecast. Loads the PRECOMPUTED forecast raster (already generated
# in Colab) rather than reloading TensorFlow at Django startup —
# keeps the server lightweight and fast to start.
# ============================================================

import os
import json
import numpy as np
import pandas as pd
import rasterio
from django.conf import settings

from routing.capacity import zone_df_attrs, CC_CONSTANTS, cattle_to_tlu, TLU_CONVERSION

DATA_DIR = settings.DATA_DIR

print("📦 [ml_predictor.py] Loading 3-month biomass forecast...")

with open(os.path.join(DATA_DIR, "manifest.json")) as f:
    manifest = json.load(f)

# --- Load the precomputed forecast raster (3 bands = +1, +2, +3 months) ---
forecast_path = os.path.join(DATA_DIR, "ml", "biomass_forecast_next_3_months.tif")

with rasterio.open(forecast_path) as src:
    biomass_forecast = np.stack([
        np.where(src.read(b + 1) == src.nodata, np.nan, src.read(b + 1))
        for b in range(3)
    ], axis=0)  # shape (3, H, W)

with rasterio.open(os.path.join(DATA_DIR, "suitability", "grazing_zones_raster.tif")) as src:
    zone_raster = src.read(1)

# Determine which calendar months the 3 forecast steps correspond to.
# The forecast was generated starting from the last available month
# in the training data (December of the final NDVI year, per Phase 7 Cell 4).
month_names = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
LAST_TRAINING_MONTH_IDX = 11  # December — matches Phase 7 Cell 4's assumption
FORECAST_MONTH_LABELS = [
    month_names[(LAST_TRAINING_MONTH_IDX + step + 1) % 12] for step in range(3)
]

print(f"✅ [ml_predictor.py] Forecast loaded — covers: {FORECAST_MONTH_LABELS}")

# ============================================================
# predict_zone_capacity_forecast — per-zone 3-month forecast
# ============================================================

def predict_zone_capacity_forecast(zone_id):
    """
    Returns the 3-month forward biomass and carrying capacity forecast
    for a given zone, using Phase 7's LSTM-predicted biomass.
    """
    zone_row = zone_df_attrs[zone_df_attrs["zone_id"] == zone_id]
    if len(zone_row) == 0:
        return {"error": f"Zone {zone_id} not found."}

    area_km2 = float(zone_row.iloc[0]["area_km2"])
    zone_mask = (zone_raster == zone_id)

    forecast_steps = []
    for step in range(3):
        mean_biomass = float(np.nanmean(biomass_forecast[step][zone_mask]))
        if np.isnan(mean_biomass):
            mean_biomass = 0.0

        cc_tlu_per_km2 = (mean_biomass * CC_CONSTANTS["UTILIZATION_RATE"] * CC_CONSTANTS["PIXEL_AREA_HA"]) \
                          / CC_CONSTANTS["MONTHLY_INTAKE_PER_TLU_KG"]
        capacity_tlu = cc_tlu_per_km2 * area_km2

        forecast_steps.append({
            "months_ahead": step + 1,
            "month_label": FORECAST_MONTH_LABELS[step],
            "predicted_biomass_kg_dm_ha": round(mean_biomass, 1),
            "predicted_capacity_tlu": round(capacity_tlu, 1),
        })

    return {
        "zone_id": zone_id,
        "area_km2": area_km2,
        "forecast": forecast_steps,
        "note": "Forecast generated by LSTM (Phase 7), iterated 3 months forward from the "
                "most recent available data. Accuracy decreases with each additional month "
                "due to compounding prediction error; rainfall is assumed similar to the "
                "most recently observed month (no true future rainfall forecast is available).",
    }

# ============================================================
# predict_zone_forecast_for_herd — forecast + can-it-sustain check
# ============================================================

def predict_zone_forecast_for_herd(zone_id, n_cattle, livestock_type="cattle_adult_zebu"):
    """Same as above, plus whether the herd would be sustained at each forecast step."""
    base_forecast = predict_zone_capacity_forecast(zone_id)
    if "error" in base_forecast:
        return base_forecast

    requested_tlu = cattle_to_tlu(n_cattle, livestock_type)

    for step in base_forecast["forecast"]:
        capacity = step["predicted_capacity_tlu"]
        step["requested_tlu"] = round(requested_tlu, 2)
        step["can_sustain"] = capacity >= requested_tlu
        step["surplus_deficit_tlu"] = round(capacity - requested_tlu, 2)

    return base_forecast


# ============================================================
# OPTIONAL — live LSTM inference (commented out; heavier startup)
# Uncomment and use this instead if you want Django to run the
# LSTM live rather than serving the precomputed forecast above.
# ============================================================

# from tensorflow.keras.models import load_model
#
# lstm_model = load_model(
#     os.path.join(DATA_DIR, "ml", "biomass_model_lstm.h5"),
#     compile=False
# )
# lstm_model.compile(optimizer="adam", loss="mse")
#
# with open(os.path.join(DATA_DIR, "ml", "lstm_normalization_stats.json")) as f:
#     norm_stats = json.load(f)
#
# def predict_live(...):
#     """Would rebuild the input sequence and call lstm_model.predict() on demand."""
#     pass